In [66]:
import pandas  as pd
import numpy as np
import biogeme.database as db
import biogeme.biogeme as bio
import biogeme.models as models
import biogeme.expressions as exp
import seaborn as sns
import matplotlib.pyplot as plt
from biogeme.expressions import Beta, DefineVariable

In [67]:
import biogeme.version as ver
from biogeme.expressions import Beta

In [68]:
df=pd.read_csv('D1.csv')

In [69]:
df

,HHID,ORIGIN_OF_TRIP,DESTINATION_OF_TRIP,TT_WALK,WALKABILITY_INDEX,TT_CYCLE,BIKEABILITY_INDEX,TT_PT,FARE_PT,WT_PT,...,CC_CAR,INCOME,GENDER,AGE,CAR OWNERSHIP,CHOSEN_MODE,AV_WALK,AV_CYCLE,AV_PT,AV_CAR
0,1,3,7,27,97,35,63,46,7,19,...,2,86,0,23,0,2,1,1,1,1
1,2,8,1,31,100,31,40,27,2,18,...,9,56,0,36,1,3,1,1,1,1
2,3,9,4,52,14,13,22,29,2,5,...,4,59,1,46,0,2,1,1,1,1
3,4,8,6,33,28,16,70,32,2,9,...,2,29,1,27,0,3,1,1,1,1
4,5,2,2,55,11,20,96,51,3,18,...,6,64,0,49,1,2,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,3,5,52,39,23,41,13,6,14,...,5,13,1,46,0,2,1,1,1,1
9996,9997,6,7,41,3,12,15,34,3,12,...,7,61,1,68,0,4,1,1,1,1
9997,9998,7,5,55,32,41,67,41,1,2,...,3,45,1,43,1,2,1,1,1,1
9998,9999,4,9,19,77,36,90,55,2,6,...,9,25,1,26,0,1,1,1,1,1
9999,10000,2,1,17,20,27,64,22,5,9,...,7,21,0,63,0,2,1,1,1,1

In [70]:
database = db.Database('dataset', df)

In [71]:
# The following statement allows you to use the names of the
# variable as Python variable.
globals().update(database.variables)

In [72]:
# display database info
display(database.getSampleSize())
display(database.variables)

10000

{'HHID': HHID,
 'ORIGIN_OF_TRIP': ORIGIN_OF_TRIP,
 'DESTINATION_OF_TRIP': DESTINATION_OF_TRIP,
 'TT_WALK': TT_WALK,
 'WALKABILITY_INDEX': WALKABILITY_INDEX,
 'TT_CYCLE': TT_CYCLE,
 'BIKEABILITY_INDEX': BIKEABILITY_INDEX,
 'TT_PT': TT_PT,
 'FARE_PT': FARE_PT,
 'WT_PT': WT_PT,
 'AT_PT': AT_PT,
 'AC_PT': AC_PT,
 'TT_CAR': TT_CAR,
 'FC_CAR': FC_CAR,
 'PC_CAR': PC_CAR,
 'CC_CAR': CC_CAR,
 'INCOME': INCOME,
 'GENDER': GENDER,
 'AGE': AGE,
 'CAR OWNERSHIP': CAR OWNERSHIP,
 'CHOSEN_MODE': CHOSEN_MODE,
 'AV_WALK': AV_WALK,
 'AV_CYCLE': AV_CYCLE,
 'AV_PT': AV_PT,
 'AV_CAR': AV_CAR}

In [83]:
# Define beta parameters
beta_WALK=Beta('beta_WALK',0,None,None,1)
beta_CYCLE=Beta('beta_CYCLE',0,None,None,0)
beta_PT=Beta('beta_PT',0,None,None,0)
beta_CAR=Beta('beta_CAR',0,None,None,0)


beta_TT_WALK = Beta('beta_TT_WALK', 0, None, None, 0)
beta_WALKABILITY_INDEX = Beta('beta_WALKABILITY_INDEX', 0, None, None, 0)
beta_AV_WALK = Beta('beta_AV_WALK', 0, None, None, 0)

beta_TT_CYCLE = Beta('beta_TT_CYCLE', 0, None, None, 0)
beta_BIKEABILITY_INDEX = Beta('beta_BIKEABILITY_INDEX', 0, None, None, 0)
beta_AV_CYCLE = Beta('beta_AV_CYCLE', 0, None, None, 0)

beta_TT_PT = Beta('beta_TT_PT', 0, None, None, 0)
beta_FARE_PT = Beta('beta_FARE_PT', 0, None, None, 0)
beta_WT_PT = Beta('beta_WT_PT', 0, None, None, 0)
beta_AT_PT = Beta('beta_AT_PT', 0, None, None, 0)
beta_AC_PT = Beta('beta_AC_PT', 0, None, None, 0)
beta_AV_PT = Beta('beta_AV_PT', 0, None, None, 0)

beta_TT_CAR = Beta('beta_TT_CAR', 0, None, None, 0)
beta_FC_CAR = Beta('beta_FC_CAR', 0, None, None, 0)
beta_PC_CAR = Beta('beta_PC_CAR', 0, None, None, 0)
beta_CC_CAR = Beta('beta_CC_CAR', 0, None, None, 0)
beta_AV_CAR = Beta('beta_AV_CAR', 0, None, None, 0)

beta_AGE = Beta('beta_AGE', 0, None, None, 0)
beta_INCOME = Beta('beta_INCOME', 0, None, None, 0)

In [88]:
# Define utility functions
V_WALK =  beta_WALK   + beta_TT_WALK  * TT_WALK  + beta_WALKABILITY_INDEX * WALKABILITY_INDEX + beta_AGE      * AGE       + beta_INCOME * INCOME
V_CYCLE = beta_CYCLE  + beta_TT_CYCLE * TT_CYCLE + beta_BIKEABILITY_INDEX * BIKEABILITY_INDEX + beta_AV_CYCLE * AV_CYCLE   + beta_AGE      * AGE       + beta_INCOME * INCOME
V_PT =    beta_PT     + beta_TT_PT    * TT_PT    + beta_FARE_PT           * FARE_PT           + beta_WT_PT    * WT_PT      + beta_AT_PT    * AT_PT     + beta_AC_PT  * AC_PT   + beta_AV_PT    * AV_PT     + beta_AGE      * AGE       + beta_INCOME * INCOME
V_CAR =   beta_CAR    + beta_TT_CAR   * TT_CAR   + beta_FC_CAR            * FC_CAR            + beta_PC_CAR   * PC_CAR     + beta_CC_CAR   * CC_CAR    + beta_AV_CAR * AV_CAR  + beta_AGE      * AGE       + beta_INCOME   * INCOME

In [89]:
# Associate utility functions with alternatives and availability conditions
V = {1: V_WALK, 2: V_CYCLE, 3: V_PT, 4: V_CAR}

In [90]:
av = {1: 1, 2: 1, 3: 1, 4: 1}

In [91]:
# Create the Biogeme logit model
logprob = models.loglogit(V, av, CHOSEN_MODE)

# Create the Biogeme object
biogeme = bio.BIOGEME(database, logprob)

In [93]:
# Estimate the parameters
results = biogeme.estimate()

# Print the estimation results
results.getEstimatedParameters()

You have not defined a name for the model. The output files are named from the model name. The default is [biogemeModelDefaultName]

                           Value   Rob. Std err    Rob. t-test  Rob. p-value
beta_AC_PT             -0.573992   4.550597e-02  -1.261356e+01  0.000000e+00
beta_AGE               -0.001368  1.797693e+308 -7.607377e-312  1.000000e+00
beta_AT_PT             -0.066275   9.078088e-03  -7.300600e+00  2.864375e-13
beta_AV_CAR             2.829249   8.466365e-02   3.341752e+01  0.000000e+00
beta_AV_CYCLE           0.022493   4.988252e-02   4.509148e-01  6.520510e-01
beta_AV_PT              2.366910   1.612514e-01   1.467839e+01  0.000000e+00
beta_BIKEABILITY_INDEX  0.005640   8.519415e-04   6.619822e+00  3.596301e-11
beta_CAR                0.037114   8.466365e-02   4.383650e-01  6.611217e-01
beta_CC_CAR            -0.128076   1.272466e-02  -1.006516e+01  0.000000e+00
beta_CYCLE              0.037645   4.988252e-02   7.546774e-01  4.504426e-01
beta_FARE_PT           -0.998482   5.846764e-02  -1.707752e+01  0.000000e+00
beta_FC_CAR            -0.559056   4.038219e-02  -1.384413e+01  0.000000e+00
beta_INCOME            -0.000273   2.054106e-16  -1.327974e+12  0.000000e+00
beta_PC_CAR            -0.234868   1.471030e-02  -1.596623e+01  0.000000e+00
beta_PT                 0.039071   1.612514e-01   2.422978e-01  8.085494e-01
beta_TT_CAR            -0.102489   2.941999e-03  -3.483658e+01  0.000000e+00
beta_TT_CYCLE          -0.073496   1.831350e-03  -4.013233e+01  0.000000e+00
beta_TT_PT             -0.068640   5.467883e-03  -1.255335e+01  0.000000e+00
beta_TT_WALK           -0.071098   1.802827e-03  -3.943718e+01  0.000000e+00
beta_WALKABILITY_INDEX  0.008796   8.445359e-04   1.041472e+01  0.000000e+00
beta_WT_PT             -0.032645   1.235746e-02  -2.641726e+00  8.248477e-03

In [113]:
import biogeme.database as db
import biogeme.biogeme as bio
import biogeme.models as models
from biogeme.expressions import Beta, DefineVariable
from scipy.optimize import minimize, approx_fprime